#ifndef	_MH_PREDEF_COMPILER_H_
#define	_MH_PREDEF_COMPILER_H_

#include "language.h"

/* compiler
 *
 *	_MH_COMPILER_MSVC_
 *	_MH_COMPILER_GNUC_
 */

#define	_MH_COMPILER_MSVC_		(1)
#define	_MH_COMPILER_GNUC_		(2)
#define	_MH_COMPILER_MINGW32_	(3)
#define	_MH_COMPILER_MINGW64_	(4)
#define	_MH_COMPILER_BORLAND_	(5)

#define	_MH_COMPILER_SUPPORT_TR1_	(1<<0)

#if		defined(_MSC_VER)

#	define	_MH_COMPILER_		_MH_COMPILER_MSVC_
#	define	_MH_COMPILER_VER_	_MSC_VER
#	define	_MH_COMPILER_NAME_	"Microsoft Visual C++"

#if	(_MSC_VER == 1500)		// 9.0 (2008)
#	define	_MH_COMPILER_SUPPORT_	(0)
#elif	(_MSC_VER == 1600)	// 10.0 (2010)
#	define	_MH_COMPILER_SUPPORT_	(_MH_CPP11_FEATURE_AUTO_|_MH_CPP11_FEATURE_DECLTYPE_|_MH_CPP11_FEATURE_NULLPTR_|_MH_CPP11_FEATURE_LAMBDA_|_MH_CPP11_FEATURE_RVALUE_REFERENCE_|_MH_CPP11_FEATURE_STATIC_ASSERT_)
#elif	(_MSC_VER == 1700)	// 11.0 (2012)
#	define	_MH_COMPILER_SUPPORT_	(_MH_CPP11_FEATURE_AUTO_|_MH_CPP11_FEATURE_DECLTYPE_|_MH_CPP11_FEATURE_NULLPTR_|_MH_CPP11_FEATURE_LAMBDA_|_MH_CPP11_FEATURE_RVALUE_REFERENCE_|_MH_CPP11_FEATURE_STATIC_ASSERT_|_MH_CPP11_FEATURE_RANGE_BASED_FOR_LOOP_|_MH_CPP11_FEATURE_OVERRIDE_FINAL_)
#elif	(_MSC_VER == 1800)	// 12.0 (2013)
#	define	_MH_COMPILER_SUPPORT_	(_MH_CPP11_FEATURE_AUTO_|_MH_CPP11_FEATURE_DECLTYPE_|_MH_CPP11_FEATURE_NULLPTR_|_MH_CPP11_FEATURE_LAMBDA_|_MH_CPP11_FEATURE_RVALUE_REFERENCE_|_MH_CPP11_FEATURE_STATIC_ASSERT_|_MH_CPP11_FEATURE_RANGE_BASED_FOR_LOOP_|_MH_CPP11_FEATURE_OVERRIDE_FINAL_)
#elif	(_MSC_VER == 1900)	// 14.0 (2015)
#	define	_MH_COMPILER_SUPPORT_	(_MH_CPP11_FEATURE_AUTO_|_MH_CPP11_FEATURE_DECLTYPE_|_MH_CPP11_FEATURE_NULLPTR_|_MH_CPP11_FEATURE_LAMBDA_|_MH_CPP11_FEATURE_RVALUE_REFERENCE_|_MH_CPP11_FEATURE_STATIC_ASSERT_|_MH_CPP11_FEATURE_RANGE_BASED_FOR_LOOP_|_MH_CPP11_FEATURE_OVERRIDE_FINAL_|_MH_CPP11_FEATURE_INLINE_NAMESPACE_)
#elif	(_MSC_VER == 1910)	// 15.0 (2017)
#	define	_MH_COMPILER_SUPPORT_	(_MH_CPP11_FEATURE_AUTO_|_MH_CPP11_FEATURE_DECLTYPE_|_MH_CPP11_FEATURE_NULLPTR_|_MH_CPP11_FEATURE_LAMBDA_|_MH_CPP11_FEATURE_RVALUE_REFERENCE_|_MH_CPP11_FEATURE_STATIC_ASSERT_|_MH_CPP11_FEATURE_RANGE_BASED_FOR_LOOP_|_MH_CPP11_FEATURE_OVERRIDE_FINAL_|_MH_CPP11_FEATURE_INLINE_NAMESPACE_)
#endif

#elif	defined(__GNUC__)

#	define	_MH_COMPILER_		_MH_COMPILER_GNUC_
#	ifdef	__GNUC_PATCHLEVEL__
#		define	_MH_COMPILER_VER_	((__GNUC__*100) + (__GNUC_MINOR__*10) + __GNUC_PATCHLEVEL__)
#	else
#		define	_MH_COMPILER_VER_	((__GNUC__*100) + (__GNUC_MINOR__*10))
#	endif
#	define	_MH_COMPILER_NAME_	"GNU C/C++"

#elif	defined(__MINGW32__) || defined(__MINGW64__)

#	ifdef	__MINGW32__
#		define	_MH_COMPILER_		_MH_COMPILER_MINGW32_
#		define	_MH_COMPILER_VER_	(__MINGW32_MAJOR_VERSION * 100 + __MINGW32_MINOR_VERSION)
#	else
#		define	_MH_COMPILER_		_MH_COMPILER_MINGW64_
#		define	_MH_COMPILER_VER_	(__MINGW64_MAJOR_VERSION * 100 + __MINGW64_MINOR_VERSION)
#	endif
#	define	_MH_COMPILER_NAME_	"MinGW"

#elif	defined(__BORLANDC__)

#	define	_MH_COMPILER_		_MH_COMPILER_BORLAND_
#	define	_MH_COMPILER_VER	__BORLANDC__
#	define	_MH_COMPILER_NAME_	"Borland C++"

#endif


#endif	/* _MH_PREDEF_COMPILER_H_ */