#ifndef	_MH_PREDEF_CONFIG_H_
#define	_MH_PREDEF_CONFIG_H_

#define	_MH_CONFIG_THREAD_SINGLE_	(0)
#define	_MH_CONFIG_THREAD_MULTI_	(1)

#define	_MH_CONFIG_THREAD_		_MH_CONFIG_THREAD_SINGLE_

/*
 *	부동소숫점의 정밀도
 */
#define	_MH_CONFIG_PRECISION_HALF_		(0)
#define	_MH_CONFIG_PRECISION_SINGLE_	(1)
#define	_MH_CONFIG_PRECISION_DOUBLE_	(2)

#define	_MH_CONFIG_PRECISION_	_MH_CONFIG_PRECISION_SINGLE_

#endif	/* _MH_PREDEF_CONFIG_H_ */